### ISSUE TITLE
trouble setting it up

### ISSUE THREAD

**Issue by killer25612082** [DevilGale/PokeCord#1]
i would really appreciated if you write up a tutorial on how to set this up

**Comment by Tadasu85** [comment]
There is one. We do however need Docs for linux/debian which if I can get it running I will work on and submit a PR.

**Comment by NovaplexGH** [comment]
I would appreciate a more in depth explanation as a person who doesn't mess with bots much and would like a good alternative that I know can remain online

**Comment by SyedAhkam** [comment]
I was able to get it running on Linux easily, Just follow the steps in the readme file and instead of the .bat file just get a process manager like pm2 and run the main.py file through it.

**Comment by SyedAhkam** [comment]
I was able to get it running on Linux easily, Just follow the steps in the readme file and instead of the .bat file just get a process manager like pm2 and run the main.py file through it.
