### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aceastig24** [DevilGale/PokeCord#12]
![ssss](https://user-images.githubusercontent.com/43810550/88577517-0abe9280-d03f-11ea-9d7b-e0ae680564c2.JPG)

**Comment by IceCruelStuff** [comment]
Did you enter your information in the `var_secrets.py` file?

**Comment by aceastig24** [comment]
> 
> 
> Did you enter your information in the `var_secrets.py` file?

imgr_client_id = None #IMGR Given (Replace with string wrapped in quotes, eg. "[value]")
imgr_client_secret = None #IMGR Given (Replace with string wrapped in quotes, eg. "[value]")
 
I do not know where to get this infos

**Comment by aceastig24** [comment]
top kek never mind google is the answer
