### ISSUE TITLE
Not understanding.

### ISSUE THREAD

**Issue by BadMoox** [DevilGale/PokeCord#14]
**Hello, so I am currently coding in PyDroid3, it's a mobile app and I can't do these commands on the terminal should I download something or there is a problem? Please help me. We would like a tutorial how to set up these codes since, some people get confused.**

![Screenshot_20200728-162307_Pydroid 3](https://user-images.githubusercontent.com/68911937/88678359-a955fc80-d0ee-11ea-8282-ff9803b50878.jpg)

**Comment by SyedAhkam** [comment]
You need to cd into the directory which you cloned using git first.
