### ISSUE TITLE
What to do imgur?

### ISSUE THREAD

**Issue by SiddharthGautam1** [DevilGale/PokeCord#18]
**_Please tell me what to do in imgur._**

**Thank You**

**Comment by DevilGale** [comment]
1. Go to https://api.imgur.com/oauth2/addclient and create an account
2. Filling out the form:
 - Type whatever name you want from App name.
 - I used OAuth 2 authorization with callback URL. The callback URL being 'https://imgur.com'
3. On submit of imgr form; in the var_secrets.py replace your imgr_client_id and imgr_client_secret

**Comment by SiddharthGautam1** [comment]
Ok Thanks!
