### ISSUE TITLE
Has this project been discontinued?

### ISSUE THREAD

**Issue by faluhub** [DevilGale/PokeCord#23]

**Comment by DevilGale** [comment]
No. I just have sprints of motivation and haven't been inspired to add anything. If a bug occurred I would try to fix that.

**Comment by MntRushmore** [comment]
Can U add better embeds @DevilGale

**Comment by DevilGale** [comment]
@WolfGamer2 Do you mean this library in particular? https://github.com/Fraserbc/BetterDiscord-Embeds

**Comment by faluhub** [comment]
I think he just means improving the embeds
