### ISSUE TITLE
Catching Pokemon

### ISSUE THREAD

**Issue by GenryMg** [DevilGale/PokeCord#6]
How can I catch pokemon using the bot? I tried `p!catch` and `p!capture` but none of them worked

**Comment by DevilGale** [comment]
Just type in the pokemon name. No command needed

**Comment by SyedAhkam** [comment]
Also, keep in mind, the default prefix is **;**
You can change it in [Config.py](https://github.com/DevilGale/PokeCord/blob/4584032addf298c28d4ae900a6092089470218e2/Config.py#L16)
