### ISSUE TITLE
;restart command does not work

### ISSUE THREAD

**Issue by gamblingrepairman** [DevilGale/PokeCord#8]
hello,

I typed in the command ;restart. This is the following output:
[Jun-21 01:57]: 'restart' by _(my username)_
C:\Program: can't open file 'Files': [Errno PS _(my cwd)_> 2] No such file or directory

**I should ask does anyone else have this issue or am I the only one seeing it?**

I was wondering if I am possibly missing a PATH variable or something else is going on. 

Thank you.

**Comment by DevilGale** [comment]
Does your path have a space in it?

**Comment by gamblingrepairman** [comment]
Sure does.

**C:\Program Files (x86)\....**

I wonder what other issues this will cause me.
